linters:
  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  NestingDepth:
    enabled: true
    max_depth: 5
